[package]
name = "acmed-dns-helper-dnspod"
version = "0.1.0"
authors = ["WANG Xuerui <git@xen0n.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
